## Exercise 1 - Basic Pandas Operations

In [ ]:
# a) Import necessary libraries

import pandas as pd

pd.set_option('display.max_rows', 1000)

In [ ]:
# b) Import dataset

df = pd.read_csv('./occupation.csv', index_col=0)

In [ ]:
# c) Print first 25 rows

df.iloc[:25]

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator     5201
9         29      M        student     1002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other     6405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer     6355
18        35      F          other    37212
19        40      M      librarian     2138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [ ]:
# d) Print last 10 rows

df.iloc[-10:]

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator     2215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [ ]:
# e) Number of observations

print(f'Number of observations in the dataset: {len(df)}')

Number of observations in the dataset: 943

In [ ]:
# e) Number of observations (alternative)

print(f'Number of observations in the dataset: {df.index.size}')

Number of observations in the dataset: 943

In [ ]:
# e) Number of observations (alternative)

print(f'Number of observations in the dataset: {df.shape[0]}')

Number of observations in the dataset: 943

In [ ]:
# f) Number of columns

print(f'Number of columns in the dataset: {df.columns.size}')

Number of columns in the dataset: 4

In [ ]:
# f) Number of columns (alternative)

print(f'Number of columns in the dataset: {df.shape[1]}')

Number of columns in the dataset: 4

In [22]:
# g) Print out name of all columns

df.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [24]:
# g) Print out name of all columns (alternative)

for colname in df.columns:
    print(colname)

age
gender
occupation
zip_code

In [ ]:
# h) How is dataset indexed
# The dataset is indexed based on user_id column

df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

In [27]:
# i) Data type of each column

df.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [29]:
# j) Print occupation column only

df.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
6          executive
7      administrator
8      administrator
9            student
10            lawyer
11             other
12             other
13          educator
14         scientist
15          educator
16     entertainment
17        programmer
18             other
19         librarian
20         homemaker
21            writer
22            writer
23            artist
24            artist
25          engineer
26          engineer
27         librarian
28            writer
29        programmer
30           student
31            artist
32           student
33           student
34     administrator
35         homemaker
36           student
37           student
38             other
39     entertainment
40         scientist
41          engineer
42     administrator
43         librarian
44        technician
45        programmer
46         marketing
47         marketing
48     administrator
49           student
50            writer
51          educator
52           student
53        programmer
54         executive
55        programmer
56         librarian
57              none
58        programmer
59          educator
60        healthcare
61          engineer
62     administrator
63         marketing
64          educator
65          educator
66           student
67           student
68           student
69          engineer
70          engineer
71         scientist
72     administrator
73           student
74         scientist
75     entertainment
76           student
77        technician
78     administrator
79     administrator
80     administrator
81           student
82        programmer
83             other
84         executive
85          educator
86     administrator
87     administrator
88         librarian
89     administrator
90          educator
91         marketing
92     entertainment
93         executive
94           student
95     administrator
96            artist
97            artist
98         executive
99           student
100        executive
101          student
102       programmer
103          student
104          student
105         engineer
106          retired
107        scientist
108         educator
109            other
110          student
111         engineer
112         salesman
113        executive
114       programmer
115         engineer
116       healthcare
117          student
118    administrator
119       programmer
120            other
121        librarian
122           writer
123           artist
124          student
125           lawyer
126           lawyer
127             none
128        marketing
129        marketing
130             none
131    administrator
132            other
133         engineer
134       programmer
135          student
136            other
137         educator
138           doctor
139          student
140          student
141       programmer
142            other
143       technician
144       programmer
145    entertainment
146           artist
147        librarian
148         engineer
149        marketing
150           artist
151    administrator
152         educator
153          student
154          student
155            other
156         educator
157         engineer
158         educator
159          student
160       programmer
161           lawyer
162           artist
163    administrator
164       healthcare
165            other
166         educator
167            other
168            other
169            other
170       healthcare
171         educator
172        marketing
173            other
174    administrator
175        scientist
176        scientist
177       programmer
178            other
179    entertainment
180    administrator
181        executive
182       programmer
183        scientist
184        librarian
185        librarian
186        executive
187         educator
188          student
189           artist
190    administrator
191    administrator
192         educator
193          student
194    administrator
195        scientist
196           writer
197       technician
198          student
199           writer
200       programmer
201           writer
202         educator
203          student
204        librarian
205           lawyer
206          student
207        marketing
208         engineer
209         educator
210         engineer
211         salesman
212         educator
213        executive
214        librarian
215       programmer
216         engineer
217            other
218    administrator
219       programmer
220        librarian
221          student
222       programmer
223          student
224         educator
225    administrator
226          student
227        executive
228          student
229        librarian
230          student
231        librarian
232        scientist
233         engineer
234          retired
235         educator
236           writer
237    administrator
238    administrator
239           artist
240         educator
241          student
242         educator
243         educator
244       technician
245          student
246          student
247         engineer
248          student
249          student
250        executive
251           doctor
252         engineer
253        librarian
254         educator
255    entertainment
256             none
257          student
258          student
259          student
260           artist
261    administrator
262          student
263       programmer
264           writer
265        executive
266    administrator
267         engineer
268         engineer
269        librarian
270          student
271         engineer
272        scientist
273            other
274          student
275         engineer
276          student
277    administrator
278        librarian
279       programmer
280        librarian
281          student
282    administrator
283       programmer
284        executive
285       programmer
286          student
287         salesman
288        marketing
289             none
290         engineer
291          student
292       programmer
293           writer
294       technician
295         educator
296    administrator
297         educator
298        executive
299           doctor
300       programmer
301          student
302         educator
303          student
304          student
305       programmer
306            other
307          student
308          retired
309        scientist
310         educator
311       technician
312            other
313        marketing
314          student
315         educator
316            other
317    administrator
318          retired
319       programmer
320          student
321         educator
322          student
323          student
324          student
325       technician
326    administrator
327          student
328    administrator
329         educator
330         educator
331    entertainment
332          student
333            other
334        librarian
335        executive
336         salesman
337        scientist
338        librarian
339           lawyer
340         engineer
341          student
342            other
343         engineer
344        librarian
345        librarian
346            other
347          student
348          student
349          retired
350          student
351         educator
352       programmer
353        scientist
354        librarian
355          student
356        homemaker
357        executive
358         educator
359          student
360            other
361          student
362        homemaker
363          student
364         engineer
365           lawyer
366          student
367          student
368          student
369          student
370           writer
371         engineer
372          student
373            other
374        executive
375    entertainment
376            other
377          student
378          student
379       programmer
380         engineer
381           artist
382         engineer
383    administrator
384       programmer
385           writer
386         salesman
387    entertainment
388            other
389           writer
390           writer
391          student
392           writer
393          student
394    administrator
395            other
396         engineer
397          student
398            other
399            other
400    administrator
401       healthcare
402         engineer
403            other
404       programmer
405       healthcare
406         educator
407         engineer
408          student
409    administrator
410           artist
411         educator
412         educator
413         educator
414       programmer
415         educator
416          student
417            other
418             none
419           lawyer
420         educator
421       programmer
422    entertainment
423            other
424        marketing
425          student
426         educator
427           doctor
428          student
429          student
430        scientist
431        marketing
432    entertainment
433           artist
434          student
435         engineer
436    administrator
437            other
438    administrator
439    administrator
440            other
441       technician
442          student
443         salesman
444           lawyer
445           writer
446         educator
447    administrator
448    entertainment
449        librarian
450         educator
451          student
452    administrator
453          student
454            other
455    administrator
456       technician
457         salesman
458       technician
459          student
460            other
461          student
462          student
463       healthcare
464           writer
465            other
466          student
467         engineer
468         engineer
469         educator
470       programmer
471          student
472          student
473          student
474        executive
475       programmer
476          student
477          student
478            other
479         educator
480          retired
481          retired
482          student
483        scientist
484          student
485         educator
486         educator
487         engineer
488       technician
489            other
490           artist
491           writer
492         educator
493         engineer
494    administrator
495         engineer
496          student
497          student
498           writer
499       programmer
500    administrator
501          student
502          student
503           writer
504           writer
505            other
506       programmer
507           writer
508        marketing
509    administrator
510            other
511          student
512            other
513    administrator
514       programmer
515        marketing
516        librarian
517          student
518           writer
519            other
520       healthcare
521          student
522         engineer
523    administrator
524         educator
525    administrator
526        marketing
527        librarian
528          student
529    administrator
530         engineer
531         salesman
532          student
533        librarian
534          student
535         educator
536         engineer
537         engineer
538        scientist
539    administrator
540         engineer
541          student
542          student
543        scientist
544            other
545       technician
546        executive
547         educator
548           writer
549        scientist
550          student
551       programmer
552            other
553         educator
554        scientist
555         educator
556         educator
557           writer
558           writer
559        executive
560          student
561         engineer
562    administrator
563        librarian
564          retired
565          student
566          student
567    entertainment
568         educator
569         educator
570         educator
571           artist
572         educator
573          retired
574         educator
575        marketing
576        executive
577          student
578    administrator
579         educator
580          student
581            other
582          student
583         engineer
584          student
585        librarian
586          student
587            other
588          student
589           lawyer
590         educator
591        librarian
592          student
593         educator
594         educator
595       programmer
596           artist
597            other
598        marketing
599          student
600       programmer
601           artist
602            other
603       programmer
604         educator
605         engineer
606       programmer
607       healthcare
608            other
609          student
610          student
611        librarian
612         educator
613        marketing
614         educator
615         educator
616        scientist
617           writer
618          student
619          student
620           writer
621          student
622       programmer
623         educator
624          student
625       programmer
626        scientist
627         engineer
628             none
629            other
630       healthcare
631          student
632          student
633       programmer
634         engineer
635            other
636         educator
637            other
638         engineer
639        librarian
640          student
641          student
642          student
643        scientist
644          retired
645       programmer
646          student
647         educator
648         engineer
649          student
650         engineer
651          retired
652            other
653        executive
654          student
655       healthcare
656         educator
657             none
658       programmer
659         educator
660          student
661       programmer
662        librarian
663            other
664         engineer
665    administrator
666    administrator
667        librarian
668           writer
669            other
670       technician
671       programmer
672    administrator
673         educator
674          student
675            other
676       programmer
677            other
678         educator
679          student
680           lawyer
681        marketing
682       programmer
683        librarian
684          student
685        librarian
686         educator
687       healthcare
688    administrator
689            other
690         salesman
691         educator
692         engineer
693       healthcare
694       programmer
695           writer
696            other
697            other
698       programmer
699            other
700          student
701        librarian
702            other
703         educator
704        librarian
705          student
706          student
707        librarian
708        homemaker
709            other
710          student
711          student
712          student
713            other
714         engineer
715       technician
716    administrator
717       technician
718       technician
719            other
720    administrator
721    entertainment
722        homemaker
723        executive
724        executive
725          student
726    administrator
727          student
728        executive
729          student
730        scientist
731         educator
732            other
733            other
734            other
735       healthcare
736           writer
737       programmer
738       technician
739       technician
740         educator
741           writer
742          student
743       programmer
744        marketing
745           writer
746         engineer
747            other
748    administrator
749            other
750    administrator
751            other
752          retired
753         salesman
754        librarian
755         educator
756             none
757          student
758          student
759          student
760            other
761          student
762    administrator
763        scientist
764         educator
765          student
766            other
767         engineer
768    administrator
769        executive
770          student
771          student
772           writer
773          student
774          student
775        executive
776        librarian
777       programmer
778          student
779          student
780       programmer
781          student
782           artist
783        marketing
784    administrator
785         engineer
786         engineer
787          student
788    administrator
789            other
790       technician
791         educator
792       programmer
793          student
794         educator
795       programmer
796           writer
797            other
798           writer
799    administrator
800       programmer
801           writer
802    administrator
803    administrator
804         educator
805            other
806        marketing
807       healthcare
808         salesman
809        marketing
810            other
811         educator
812       technician
813          student
814            other
815            other
816            other
817          student
818        librarian
819    administrator
820          student
821         engineer
822        librarian
823           artist
824            other
825         engineer
826           artist
827         engineer
828        librarian
829           writer
830       programmer
831            other
832       technician
833           writer
834            other
835        executive
836           artist
837           artist
838          student
839    entertainment
840           artist
841           doctor
842           writer
843        librarian
844         engineer
845           doctor
846           lawyer
847          student
848         engineer
849          student
850       technician
851            other
852    administrator
853           writer
854          student
855        librarian
856        marketing
857    administrator
858         educator
859            other
860          retired
861          student
862        executive
863          student
864       programmer
865           artist
866            other
867        scientist
868       programmer
869          student
870          student
871        executive
872          student
873    administrator
874        scientist
875          student
876            other
877            other
878         educator
879    administrator
880          student
881        marketing
882         engineer
883        librarian
884         engineer
885            other
886          student
887          student
888        scientist
889       technician
890          student
891    administrator
892            other
893          student
894         educator
895        librarian
896           writer
897            other
898        homemaker
899            other
900          retired
901        executive
902           artist
903         educator
904          student
905            other
906        librarian
907            other
908        librarian
909         educator
910       healthcare
911           writer
912            other
913          student
914            other
915    entertainment
916         engineer
917          student
918        scientist
919            other
920           artist
921          student
922    administrator
923          student
924            other
925         salesman
926    entertainment
927       programmer
928          student
929        scientist
930        scientist
931         educator
932         educator
933          student
934         engineer
935           doctor
936            other
937         educator
938       technician
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, dtype: object

In [30]:
# j) Print occupation column only (alternative)

df['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
6          executive
7      administrator
8      administrator
9            student
10            lawyer
11             other
12             other
13          educator
14         scientist
15          educator
16     entertainment
17        programmer
18             other
19         librarian
20         homemaker
21            writer
22            writer
23            artist
24            artist
25          engineer
26          engineer
27         librarian
28            writer
29        programmer
30           student
31            artist
32           student
33           student
34     administrator
35         homemaker
36           student
37           student
38             other
39     entertainment
40         scientist
41          engineer
42     administrator
43         librarian
44        technician
45        programmer
46         marketing
47         marketing
48     administrator
49           student
50            writer
51          educator
52           student
53        programmer
54         executive
55        programmer
56         librarian
57              none
58        programmer
59          educator
60        healthcare
61          engineer
62     administrator
63         marketing
64          educator
65          educator
66           student
67           student
68           student
69          engineer
70          engineer
71         scientist
72     administrator
73           student
74         scientist
75     entertainment
76           student
77        technician
78     administrator
79     administrator
80     administrator
81           student
82        programmer
83             other
84         executive
85          educator
86     administrator
87     administrator
88         librarian
89     administrator
90          educator
91         marketing
92     entertainment
93         executive
94           student
95     administrator
96            artist
97            artist
98         executive
99           student
100        executive
101          student
102       programmer
103          student
104          student
105         engineer
106          retired
107        scientist
108         educator
109            other
110          student
111         engineer
112         salesman
113        executive
114       programmer
115         engineer
116       healthcare
117          student
118    administrator
119       programmer
120            other
121        librarian
122           writer
123           artist
124          student
125           lawyer
126           lawyer
127             none
128        marketing
129        marketing
130             none
131    administrator
132            other
133         engineer
134       programmer
135          student
136            other
137         educator
138           doctor
139          student
140          student
141       programmer
142            other
143       technician
144       programmer
145    entertainment
146           artist
147        librarian
148         engineer
149        marketing
150           artist
151    administrator
152         educator
153          student
154          student
155            other
156         educator
157         engineer
158         educator
159          student
160       programmer
161           lawyer
162           artist
163    administrator
164       healthcare
165            other
166         educator
167            other
168            other
169            other
170       healthcare
171         educator
172        marketing
173            other
174    administrator
175        scientist
176        scientist
177       programmer
178            other
179    entertainment
180    administrator
181        executive
182       programmer
183        scientist
184        librarian
185        librarian
186        executive
187         educator
188          student
189           artist
190    administrator
191    administrator
192         educator
193          student
194    administrator
195        scientist
196           writer
197       technician
198          student
199           writer
200       programmer
201           writer
202         educator
203          student
204        librarian
205           lawyer
206          student
207        marketing
208         engineer
209         educator
210         engineer
211         salesman
212         educator
213        executive
214        librarian
215       programmer
216         engineer
217            other
218    administrator
219       programmer
220        librarian
221          student
222       programmer
223          student
224         educator
225    administrator
226          student
227        executive
228          student
229        librarian
230          student
231        librarian
232        scientist
233         engineer
234          retired
235         educator
236           writer
237    administrator
238    administrator
239           artist
240         educator
241          student
242         educator
243         educator
244       technician
245          student
246          student
247         engineer
248          student
249          student
250        executive
251           doctor
252         engineer
253        librarian
254         educator
255    entertainment
256             none
257          student
258          student
259          student
260           artist
261    administrator
262          student
263       programmer
264           writer
265        executive
266    administrator
267         engineer
268         engineer
269        librarian
270          student
271         engineer
272        scientist
273            other
274          student
275         engineer
276          student
277    administrator
278        librarian
279       programmer
280        librarian
281          student
282    administrator
283       programmer
284        executive
285       programmer
286          student
287         salesman
288        marketing
289             none
290         engineer
291          student
292       programmer
293           writer
294       technician
295         educator
296    administrator
297         educator
298        executive
299           doctor
300       programmer
301          student
302         educator
303          student
304          student
305       programmer
306            other
307          student
308          retired
309        scientist
310         educator
311       technician
312            other
313        marketing
314          student
315         educator
316            other
317    administrator
318          retired
319       programmer
320          student
321         educator
322          student
323          student
324          student
325       technician
326    administrator
327          student
328    administrator
329         educator
330         educator
331    entertainment
332          student
333            other
334        librarian
335        executive
336         salesman
337        scientist
338        librarian
339           lawyer
340         engineer
341          student
342            other
343         engineer
344        librarian
345        librarian
346            other
347          student
348          student
349          retired
350          student
351         educator
352       programmer
353        scientist
354        librarian
355          student
356        homemaker
357        executive
358         educator
359          student
360            other
361          student
362        homemaker
363          student
364         engineer
365           lawyer
366          student
367          student
368          student
369          student
370           writer
371         engineer
372          student
373            other
374        executive
375    entertainment
376            other
377          student
378          student
379       programmer
380         engineer
381           artist
382         engineer
383    administrator
384       programmer
385           writer
386         salesman
387    entertainment
388            other
389           writer
390           writer
391          student
392           writer
393          student
394    administrator
395            other
396         engineer
397          student
398            other
399            other
400    administrator
401       healthcare
402         engineer
403            other
404       programmer
405       healthcare
406         educator
407         engineer
408          student
409    administrator
410           artist
411         educator
412         educator
413         educator
414       programmer
415         educator
416          student
417            other
418             none
419           lawyer
420         educator
421       programmer
422    entertainment
423            other
424        marketing
425          student
426         educator
427           doctor
428          student
429          student
430        scientist
431        marketing
432    entertainment
433           artist
434          student
435         engineer
436    administrator
437            other
438    administrator
439    administrator
440            other
441       technician
442          student
443         salesman
444           lawyer
445           writer
446         educator
447    administrator
448    entertainment
449        librarian
450         educator
451          student
452    administrator
453          student
454            other
455    administrator
456       technician
457         salesman
458       technician
459          student
460            other
461          student
462          student
463       healthcare
464           writer
465            other
466          student
467         engineer
468         engineer
469         educator
470       programmer
471          student
472          student
473          student
474        executive
475       programmer
476          student
477          student
478            other
479         educator
480          retired
481          retired
482          student
483        scientist
484          student
485         educator
486         educator
487         engineer
488       technician
489            other
490           artist
491           writer
492         educator
493         engineer
494    administrator
495         engineer
496          student
497          student
498           writer
499       programmer
500    administrator
501          student
502          student
503           writer
504           writer
505            other
506       programmer
507           writer
508        marketing
509    administrator
510            other
511          student
512            other
513    administrator
514       programmer
515        marketing
516        librarian
517          student
518           writer
519            other
520       healthcare
521          student
522         engineer
523    administrator
524         educator
525    administrator
526        marketing
527        librarian
528          student
529    administrator
530         engineer
531         salesman
532          student
533        librarian
534          student
535         educator
536         engineer
537         engineer
538        scientist
539    administrator
540         engineer
541          student
542          student
543        scientist
544            other
545       technician
546        executive
547         educator
548           writer
549        scientist
550          student
551       programmer
552            other
553         educator
554        scientist
555         educator
556         educator
557           writer
558           writer
559        executive
560          student
561         engineer
562    administrator
563        librarian
564          retired
565          student
566          student
567    entertainment
568         educator
569         educator
570         educator
571           artist
572         educator
573          retired
574         educator
575        marketing
576        executive
577          student
578    administrator
579         educator
580          student
581            other
582          student
583         engineer
584          student
585        librarian
586          student
587            other
588          student
589           lawyer
590         educator
591        librarian
592          student
593         educator
594         educator
595       programmer
596           artist
597            other
598        marketing
599          student
600       programmer
601           artist
602            other
603       programmer
604         educator
605         engineer
606       programmer
607       healthcare
608            other
609          student
610          student
611        librarian
612         educator
613        marketing
614         educator
615         educator
616        scientist
617           writer
618          student
619          student
620           writer
621          student
622       programmer
623         educator
624          student
625       programmer
626        scientist
627         engineer
628             none
629            other
630       healthcare
631          student
632          student
633       programmer
634         engineer
635            other
636         educator
637            other
638         engineer
639        librarian
640          student
641          student
642          student
643        scientist
644          retired
645       programmer
646          student
647         educator
648         engineer
649          student
650         engineer
651          retired
652            other
653        executive
654          student
655       healthcare
656         educator
657             none
658       programmer
659         educator
660          student
661       programmer
662        librarian
663            other
664         engineer
665    administrator
666    administrator
667        librarian
668           writer
669            other
670       technician
671       programmer
672    administrator
673         educator
674          student
675            other
676       programmer
677            other
678         educator
679          student
680           lawyer
681        marketing
682       programmer
683        librarian
684          student
685        librarian
686         educator
687       healthcare
688    administrator
689            other
690         salesman
691         educator
692         engineer
693       healthcare
694       programmer
695           writer
696            other
697            other
698       programmer
699            other
700          student
701        librarian
702            other
703         educator
704        librarian
705          student
706          student
707        librarian
708        homemaker
709            other
710          student
711          student
712          student
713            other
714         engineer
715       technician
716    administrator
717       technician
718       technician
719            other
720    administrator
721    entertainment
722        homemaker
723        executive
724        executive
725          student
726    administrator
727          student
728        executive
729          student
730        scientist
731         educator
732            other
733            other
734            other
735       healthcare
736           writer
737       programmer
738       technician
739       technician
740         educator
741           writer
742          student
743       programmer
744        marketing
745           writer
746         engineer
747            other
748    administrator
749            other
750    administrator
751            other
752          retired
753         salesman
754        librarian
755         educator
756             none
757          student
758          student
759          student
760            other
761          student
762    administrator
763        scientist
764         educator
765          student
766            other
767         engineer
768    administrator
769        executive
770          student
771          student
772           writer
773          student
774          student
775        executive
776        librarian
777       programmer
778          student
779          student
780       programmer
781          student
782           artist
783        marketing
784    administrator
785         engineer
786         engineer
787          student
788    administrator
789            other
790       technician
791         educator
792       programmer
793          student
794         educator
795       programmer
796           writer
797            other
798           writer
799    administrator
800       programmer
801           writer
802    administrator
803    administrator
804         educator
805            other
806        marketing
807       healthcare
808         salesman
809        marketing
810            other
811         educator
812       technician
813          student
814            other
815            other
816            other
817          student
818        librarian
819    administrator
820          student
821         engineer
822        librarian
823           artist
824            other
825         engineer
826           artist
827         engineer
828        librarian
829           writer
830       programmer
831            other
832       technician
833           writer
834            other
835        executive
836           artist
837           artist
838          student
839    entertainment
840           artist
841           doctor
842           writer
843        librarian
844         engineer
845           doctor
846           lawyer
847          student
848         engineer
849          student
850       technician
851            other
852    administrator
853           writer
854          student
855        librarian
856        marketing
857    administrator
858         educator
859            other
860          retired
861          student
862        executive
863          student
864       programmer
865           artist
866            other
867        scientist
868       programmer
869          student
870          student
871        executive
872          student
873    administrator
874        scientist
875          student
876            other
877            other
878         educator
879    administrator
880          student
881        marketing
882         engineer
883        librarian
884         engineer
885            other
886          student
887          student
888        scientist
889       technician
890          student
891    administrator
892            other
893          student
894         educator
895        librarian
896           writer
897            other
898        homemaker
899            other
900          retired
901        executive
902           artist
903         educator
904          student
905            other
906        librarian
907            other
908        librarian
909         educator
910       healthcare
911           writer
912            other
913          student
914            other
915    entertainment
916         engineer
917          student
918        scientist
919            other
920           artist
921          student
922    administrator
923          student
924            other
925         salesman
926    entertainment
927       programmer
928          student
929        scientist
930        scientist
931         educator
932         educator
933          student
934         engineer
935           doctor
936            other
937         educator
938       technician
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, dtype: object

In [33]:
# j) Print occupation column only (alternative)

df.iloc[:, 2]

user_id
1         technician
2              other
3             writer
4         technician
5              other
6          executive
7      administrator
8      administrator
9            student
10            lawyer
11             other
12             other
13          educator
14         scientist
15          educator
16     entertainment
17        programmer
18             other
19         librarian
20         homemaker
21            writer
22            writer
23            artist
24            artist
25          engineer
26          engineer
27         librarian
28            writer
29        programmer
30           student
31            artist
32           student
33           student
34     administrator
35         homemaker
36           student
37           student
38             other
39     entertainment
40         scientist
41          engineer
42     administrator
43         librarian
44        technician
45        programmer
46         marketing
47         marketing
48     administrator
49           student
50            writer
51          educator
52           student
53        programmer
54         executive
55        programmer
56         librarian
57              none
58        programmer
59          educator
60        healthcare
61          engineer
62     administrator
63         marketing
64          educator
65          educator
66           student
67           student
68           student
69          engineer
70          engineer
71         scientist
72     administrator
73           student
74         scientist
75     entertainment
76           student
77        technician
78     administrator
79     administrator
80     administrator
81           student
82        programmer
83             other
84         executive
85          educator
86     administrator
87     administrator
88         librarian
89     administrator
90          educator
91         marketing
92     entertainment
93         executive
94           student
95     administrator
96            artist
97            artist
98         executive
99           student
100        executive
101          student
102       programmer
103          student
104          student
105         engineer
106          retired
107        scientist
108         educator
109            other
110          student
111         engineer
112         salesman
113        executive
114       programmer
115         engineer
116       healthcare
117          student
118    administrator
119       programmer
120            other
121        librarian
122           writer
123           artist
124          student
125           lawyer
126           lawyer
127             none
128        marketing
129        marketing
130             none
131    administrator
132            other
133         engineer
134       programmer
135          student
136            other
137         educator
138           doctor
139          student
140          student
141       programmer
142            other
143       technician
144       programmer
145    entertainment
146           artist
147        librarian
148         engineer
149        marketing
150           artist
151    administrator
152         educator
153          student
154          student
155            other
156         educator
157         engineer
158         educator
159          student
160       programmer
161           lawyer
162           artist
163    administrator
164       healthcare
165            other
166         educator
167            other
168            other
169            other
170       healthcare
171         educator
172        marketing
173            other
174    administrator
175        scientist
176        scientist
177       programmer
178            other
179    entertainment
180    administrator
181        executive
182       programmer
183        scientist
184        librarian
185        librarian
186        executive
187         educator
188          student
189           artist
190    administrator
191    administrator
192         educator
193          student
194    administrator
195        scientist
196           writer
197       technician
198          student
199           writer
200       programmer
201           writer
202         educator
203          student
204        librarian
205           lawyer
206          student
207        marketing
208         engineer
209         educator
210         engineer
211         salesman
212         educator
213        executive
214        librarian
215       programmer
216         engineer
217            other
218    administrator
219       programmer
220        librarian
221          student
222       programmer
223          student
224         educator
225    administrator
226          student
227        executive
228          student
229        librarian
230          student
231        librarian
232        scientist
233         engineer
234          retired
235         educator
236           writer
237    administrator
238    administrator
239           artist
240         educator
241          student
242         educator
243         educator
244       technician
245          student
246          student
247         engineer
248          student
249          student
250        executive
251           doctor
252         engineer
253        librarian
254         educator
255    entertainment
256             none
257          student
258          student
259          student
260           artist
261    administrator
262          student
263       programmer
264           writer
265        executive
266    administrator
267         engineer
268         engineer
269        librarian
270          student
271         engineer
272        scientist
273            other
274          student
275         engineer
276          student
277    administrator
278        librarian
279       programmer
280        librarian
281          student
282    administrator
283       programmer
284        executive
285       programmer
286          student
287         salesman
288        marketing
289             none
290         engineer
291          student
292       programmer
293           writer
294       technician
295         educator
296    administrator
297         educator
298        executive
299           doctor
300       programmer
301          student
302         educator
303          student
304          student
305       programmer
306            other
307          student
308          retired
309        scientist
310         educator
311       technician
312            other
313        marketing
314          student
315         educator
316            other
317    administrator
318          retired
319       programmer
320          student
321         educator
322          student
323          student
324          student
325       technician
326    administrator
327          student
328    administrator
329         educator
330         educator
331    entertainment
332          student
333            other
334        librarian
335        executive
336         salesman
337        scientist
338        librarian
339           lawyer
340         engineer
341          student
342            other
343         engineer
344        librarian
345        librarian
346            other
347          student
348          student
349          retired
350          student
351         educator
352       programmer
353        scientist
354        librarian
355          student
356        homemaker
357        executive
358         educator
359          student
360            other
361          student
362        homemaker
363          student
364         engineer
365           lawyer
366          student
367          student
368          student
369          student
370           writer
371         engineer
372          student
373            other
374        executive
375    entertainment
376            other
377          student
378          student
379       programmer
380         engineer
381           artist
382         engineer
383    administrator
384       programmer
385           writer
386         salesman
387    entertainment
388            other
389           writer
390           writer
391          student
392           writer
393          student
394    administrator
395            other
396         engineer
397          student
398            other
399            other
400    administrator
401       healthcare
402         engineer
403            other
404       programmer
405       healthcare
406         educator
407         engineer
408          student
409    administrator
410           artist
411         educator
412         educator
413         educator
414       programmer
415         educator
416          student
417            other
418             none
419           lawyer
420         educator
421       programmer
422    entertainment
423            other
424        marketing
425          student
426         educator
427           doctor
428          student
429          student
430        scientist
431        marketing
432    entertainment
433           artist
434          student
435         engineer
436    administrator
437            other
438    administrator
439    administrator
440            other
441       technician
442          student
443         salesman
444           lawyer
445           writer
446         educator
447    administrator
448    entertainment
449        librarian
450         educator
451          student
452    administrator
453          student
454            other
455    administrator
456       technician
457         salesman
458       technician
459          student
460            other
461          student
462          student
463       healthcare
464           writer
465            other
466          student
467         engineer
468         engineer
469         educator
470       programmer
471          student
472          student
473          student
474        executive
475       programmer
476          student
477          student
478            other
479         educator
480          retired
481          retired
482          student
483        scientist
484          student
485         educator
486         educator
487         engineer
488       technician
489            other
490           artist
491           writer
492         educator
493         engineer
494    administrator
495         engineer
496          student
497          student
498           writer
499       programmer
500    administrator
501          student
502          student
503           writer
504           writer
505            other
506       programmer
507           writer
508        marketing
509    administrator
510            other
511          student
512            other
513    administrator
514       programmer
515        marketing
516        librarian
517          student
518           writer
519            other
520       healthcare
521          student
522         engineer
523    administrator
524         educator
525    administrator
526        marketing
527        librarian
528          student
529    administrator
530         engineer
531         salesman
532          student
533        librarian
534          student
535         educator
536         engineer
537         engineer
538        scientist
539    administrator
540         engineer
541          student
542          student
543        scientist
544            other
545       technician
546        executive
547         educator
548           writer
549        scientist
550          student
551       programmer
552            other
553         educator
554        scientist
555         educator
556         educator
557           writer
558           writer
559        executive
560          student
561         engineer
562    administrator
563        librarian
564          retired
565          student
566          student
567    entertainment
568         educator
569         educator
570         educator
571           artist
572         educator
573          retired
574         educator
575        marketing
576        executive
577          student
578    administrator
579         educator
580          student
581            other
582          student
583         engineer
584          student
585        librarian
586          student
587            other
588          student
589           lawyer
590         educator
591        librarian
592          student
593         educator
594         educator
595       programmer
596           artist
597            other
598        marketing
599          student
600       programmer
601           artist
602            other
603       programmer
604         educator
605         engineer
606       programmer
607       healthcare
608            other
609          student
610          student
611        librarian
612         educator
613        marketing
614         educator
615         educator
616        scientist
617           writer
618          student
619          student
620           writer
621          student
622       programmer
623         educator
624          student
625       programmer
626        scientist
627         engineer
628             none
629            other
630       healthcare
631          student
632          student
633       programmer
634         engineer
635            other
636         educator
637            other
638         engineer
639        librarian
640          student
641          student
642          student
643        scientist
644          retired
645       programmer
646          student
647         educator
648         engineer
649          student
650         engineer
651          retired
652            other
653        executive
654          student
655       healthcare
656         educator
657             none
658       programmer
659         educator
660          student
661       programmer
662        librarian
663            other
664         engineer
665    administrator
666    administrator
667        librarian
668           writer
669            other
670       technician
671       programmer
672    administrator
673         educator
674          student
675            other
676       programmer
677            other
678         educator
679          student
680           lawyer
681        marketing
682       programmer
683        librarian
684          student
685        librarian
686         educator
687       healthcare
688    administrator
689            other
690         salesman
691         educator
692         engineer
693       healthcare
694       programmer
695           writer
696            other
697            other
698       programmer
699            other
700          student
701        librarian
702            other
703         educator
704        librarian
705          student
706          student
707        librarian
708        homemaker
709            other
710          student
711          student
712          student
713            other
714         engineer
715       technician
716    administrator
717       technician
718       technician
719            other
720    administrator
721    entertainment
722        homemaker
723        executive
724        executive
725          student
726    administrator
727          student
728        executive
729          student
730        scientist
731         educator
732            other
733            other
734            other
735       healthcare
736           writer
737       programmer
738       technician
739       technician
740         educator
741           writer
742          student
743       programmer
744        marketing
745           writer
746         engineer
747            other
748    administrator
749            other
750    administrator
751            other
752          retired
753         salesman
754        librarian
755         educator
756             none
757          student
758          student
759          student
760            other
761          student
762    administrator
763        scientist
764         educator
765          student
766            other
767         engineer
768    administrator
769        executive
770          student
771          student
772           writer
773          student
774          student
775        executive
776        librarian
777       programmer
778          student
779          student
780       programmer
781          student
782           artist
783        marketing
784    administrator
785         engineer
786         engineer
787          student
788    administrator
789            other
790       technician
791         educator
792       programmer
793          student
794         educator
795       programmer
796           writer
797            other
798           writer
799    administrator
800       programmer
801           writer
802    administrator
803    administrator
804         educator
805            other
806        marketing
807       healthcare
808         salesman
809        marketing
810            other
811         educator
812       technician
813          student
814            other
815            other
816            other
817          student
818        librarian
819    administrator
820          student
821         engineer
822        librarian
823           artist
824            other
825         engineer
826           artist
827         engineer
828        librarian
829           writer
830       programmer
831            other
832       technician
833           writer
834            other
835        executive
836           artist
837           artist
838          student
839    entertainment
840           artist
841           doctor
842           writer
843        librarian
844         engineer
845           doctor
846           lawyer
847          student
848         engineer
849          student
850       technician
851            other
852    administrator
853           writer
854          student
855        librarian
856        marketing
857    administrator
858         educator
859            other
860          retired
861          student
862        executive
863          student
864       programmer
865           artist
866            other
867        scientist
868       programmer
869          student
870          student
871        executive
872          student
873    administrator
874        scientist
875          student
876            other
877            other
878         educator
879    administrator
880          student
881        marketing
882         engineer
883        librarian
884         engineer
885            other
886          student
887          student
888        scientist
889       technician
890          student
891    administrator
892            other
893          student
894         educator
895        librarian
896           writer
897            other
898        homemaker
899            other
900          retired
901        executive
902           artist
903         educator
904          student
905            other
906        librarian
907            other
908        librarian
909         educator
910       healthcare
911           writer
912            other
913          student
914            other
915    entertainment
916         engineer
917          student
918        scientist
919            other
920           artist
921          student
922    administrator
923          student
924            other
925         salesman
926    entertainment
927       programmer
928          student
929        scientist
930        scientist
931         educator
932         educator
933          student
934         engineer
935           doctor
936            other
937         educator
938       technician
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, dtype: object

In [41]:
# k) Number of different occupations
print(df['occupation'].describe())
print('')
print(f'Number of unique occupations: {df['occupation'].nunique()}')
print('')
print(f'Unique occupations: {df['occupation'].unique()}')

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

Number of unique occupations: 21

Unique occupations: ['technician' 'other' 'writer' 'executive' 'administrator' 'student'
 'lawyer' 'educator' 'scientist' 'entertainment' 'programmer' 'librarian'
 'homemaker' 'artist' 'engineer' 'marketing' 'none' 'healthcare' 'retired'
 'salesman' 'doctor']

In [44]:
# l) Print list of users aged 50 and above. Also print their quantity. 

print(df[df['age'] >= 50])

print(f'Quantity of users aged 50 and above: {len(df[df['age'] >= 50])}')

         age gender     occupation zip_code
user_id
2         53      F          other    94043
7         57      M  administrator    91344
10        53      M         lawyer    90703
47        53      M      marketing     7102
60        50      M     healthcare     6472
65        51      F       educator    48118
82        50      M     programmer    22902
85        51      M       educator    20003
90        60      M       educator    78155
91        55      M      marketing     1913
106       61      M        retired    55125
111       57      M       engineer    90630
121       54      M      librarian    99603
131       59      F  administrator    15237
133       53      M       engineer    78602
136       51      M          other    97365
137       50      M       educator    84408
144       53      M     programmer    20910
157       57      M       engineer    70808
158       50      M       educator    27606
161       50      M         lawyer    55104
169       52      F          other    53705
170       53      F     healthcare    30067
172       55      M      marketing    22207
173       56      M          other    22306
185       53      F      librarian    97403
197       55      M     technician    75094
204       52      F      librarian    10960
211       66      M       salesman    32605
225       51      F  administrator    58202
234       60      M        retired    94702
266       62      F  administrator    78756
271       51      M       engineer    22932
273       50      F          other    10016
308       60      M        retired    95076
318       65      M        retired     6518
328       51      M  administrator     6779
349       68      M        retired    61455
351       61      M       educator    49938
360       51      M          other    98027
364       63      M       engineer     1810
370       52      M         writer     8534
384       52      M     programmer    45218
392       52      M         writer    59801
396       57      M       engineer    94551
406       52      M       educator    93109
413       55      M       educator    78212
418       55      F           none    21206
420       53      M       educator     2140
423       64      M          other    91606
426       55      M       educator     1602
427       51      M         doctor    85258
438       51      F  administrator    43204
441       50      M     technician    55013
444       51      F         lawyer    53202
446       57      M       educator    60201
454       57      M          other    97330
464       60      M         writer    94583
469       60      M       educator    78628
474       51      M      executive    93711
480       57      M        retired    98257
481       73      M        retired    37771
489       55      M          other    45218
492       57      M       educator    94618
503       50      F         writer    27514
515       53      M      marketing    49508
516       53      F      librarian    10021
520       62      M     healthcare    12603
523       50      F  administrator     4102
524       56      M       educator     2159
539       53      F  administrator    80303
547       50      M       educator    14534
548       51      M         writer    95468
553       58      M       educator    62901
558       56      F         writer    63132
559       69      M      executive    10022
562       54      F  administrator    20879
564       65      M        retired    94591
572       51      M       educator    20003
573       68      M        retired    48911
574       56      M       educator    53188
585       69      M      librarian    98501
590       50      M       educator    82435
591       57      F      librarian    92093
614       54      M       educator    80227
616       55      M      scientist    50613
623       50      F       educator    60187
644       51      M        retired    63645
651       65      M        retired     2903
655       50      F     healthcare    60657
662       55      M      librarian    19102
672       54      F  administrator    90095
673       51      M       educator    22906
678       50      M       educator    61462
694       60      M     programmer     6365
696       55      M          other    94920
701       51      F      librarian    56321
704       51      F      librarian    91105
707       56      F      librarian    19146
722       50      F      homemaker    17331
728       58      M      executive    94306
752       60      M        retired    21201
753       56      M       salesman    91206
754       59      F      librarian    62901
767       70      M       engineer        0
772       50      M         writer    27105
777       63      M     programmer     1810
788       51      M  administrator     5779
803       70      M  administrator    78212
809       50      F      marketing    30803
810       55      F          other    80526
819       59      M  administrator    40205
845       64      M         doctor    97405
855       53      M      librarian     4988
858       63      M       educator     9645
860       70      F        retired    48322
878       50      F       educator    98027
891       51      F  administrator     3062
900       60      M        retired    18505
909       50      F       educator    53171
912       51      M          other     6512
915       50      M  entertainment    60614
931       60      M       educator    33556
932       58      M       educator     6437
934       61      M       engineer    22902
Quantity of users aged 50 and above: 125

In [46]:
# m) Descriptive statistics of dataset
df.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [48]:
# n) Print descriptive stats for all columns in dataset
df.describe(include='all)

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [51]:
# o) Print the descriptive stats only for occupation column
df.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [52]:
# o) Print the descriptive stats only for occupation column (alternative)
df['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [ ]:
# p) Mean of age of users
print(f'Mean age of users; {df.age.mean}')

Mean age of users; <bound method Series.mean of user_id
1      24
2      53
3      23
4      24
5      33
6      42
7      57
8      36
9      29
10     53
11     39
12     28
13     47
14     45
15     49
16     21
17     30
18     35
19     40
20     42
21     26
22     25
23     30
24     21
25     39
26     49
27     40
28     32
29     41
30      7
31     24
32     28
33     23
34     38
35     20
36     19
37     23
38     28
39     41
40     38
41     33
42     30
43     29
44     26
45     29
46     27
47     53
48     45
49     23
50     21
51     28
52     18
53     26
54     22
55     37
56     25
57     16
58     27
59     49
60     50
61     36
62     27
63     31
64     32
65     51
66     23
67     17
68     19
69     24
70     27
71     39
72     48
73     24
74     39
75     24
76     20
77     30
78     26
79     39
80     34
81     21
82     50
83     40
84     32
85     51
86     26
87     47
88     49
89     43
90     60
91     55
92     32
93     48
94     26
95     31
96     25
97     43
98     49
99     20
100    36
101    15
102    38
103    26
104    27
105    24
106    61
107    39
108    44
109    29
110    19
111    57
112    30
113    47
114    27
115    31
116    40
117    20
118    21
119    32
120    47
121    54
122    32
123    48
124    34
125    30
126    28
127    33
128    24
129    36
130    20
131    59
132    24
133    53
134    31
135    23
136    51
137    50
138    46
139    20
140    30
141    49
142    13
143    42
144    53
145    31
146    45
147    40
148    33
149    35
150    20
151    38
152    33
153    25
154    25
155    32
156    25
157    57
158    50
159    23
160    27
161    50
162    25
163    49
164    47
165    20
166    47
167    37
168    48
169    52
170    53
171    48
172    55
173    56
174    30
175    26
176    28
177    20
178    26
179    15
180    22
181    26
182    36
183    33
184    37
185    53
186    39
187    26
188    42
189    32
190    30
191    33
192    42
193    29
194    38
195    42
196    49
197    55
198    21
199    30
200    40
201    27
202    41
203    25
204    52
205    47
206    14
207    39
208    43
209    33
210    39
211    66
212    49
213    33
214    26
215    35
216    22
217    22
218    37
219    32
220    30
221    19
222    29
223    19
224    31
225    51
226    28
227    46
228    21
229    29
230    28
231    48
232    45
233    38
234    60
235    37
236    44
237    49
238    42
239    39
240    23
241    26
242    33
243    33
244    28
245    22
246    19
247    28
248    25
249    25
250    29
251    28
252    42
253    26
254    44
255    23
256    35
257    17
258    19
259    21
260    40
261    28
262    19
263    41
264    36
265    26
266    62
267    23
268    24
269    31
270    18
271    51
272    33
273    50
274    20
275    38
276    21
277    35
278    37
279    33
280    30
281    15
282    22
283    28
284    40
285    25
286    27
287    21
288    34
289    11
290    40
291    19
292    35
293    24
294    34
295    31
296    43
297    29
298    44
299    29
300    26
301    24
302    42
303    19
304    22
305    23
306    45
307    25
308    60
309    40
310    37
311    32
312    48
313    41
314    20
315    31
316    43
317    22
318    65
319    38
320    19
321    49
322    20
323    21
324    21
325    48
326    41
327    22
328    51
329    48
330    35
331    33
332    20
333    47
334    32
335    45
336    23
337    37
338    39
339    35
340    46
341    17
342    25
343    43
344    30
345    28
346    34
347    18
348    24
349    68
350    32
351    61
352    37
353    25
354    29
355    25
356    32
357    26
358    40
359    22
360    51
361    22
362    35
363    20
364    63
365    29
366    20
367    17
368    18
369    24
370    52
371    36
372    25
373    24
374    36
375    17
376    28
377    22
378    35
379    44
380    32
381    33
382    45
383    42
384    52
385    36
386    36
387    33
388    31
389    44
390    42
391    23
392    52
393    19
394    25
395    43
396    57
397    17
398    40
399    25
400    33
401    46
402    30
403    37
404    29
405    22
406    52
407    29
408    23
409    48
410    30
411    34
412    25
413    55
414    24
415    39
416    20
417    27
418    55
419    37
420    53
421    38
422    26
423    64
424    36
425    19
426    55
427    51
428    28
429    27
430    38
431    24
432    22
433    27
434    16
435    24
436    30
437    27
438    51
439    23
440    30
441    50
442    22
443    35
444    51
445    21
446    57
447    30
448    23
449    23
450    35
451    16
452    35
453    18
454    57
455    48
456    24
457    33
458    47
459    22
460    44
461    15
462    19
463    48
464    60
465    32
466    22
467    29
468    28
469    60
470    24
471    10
472    24
473    29
474    51
475    30
476    28
477    23
478    29
479    30
480    57
481    73
482    18
483    29
484    27
485    44
486    39
487    22
488    48
489    55
490    29
491    43
492    57
493    22
494    38
495    29
496    21
497    20
498    26
499    42
500    28
501    22
502    22
503    50
504    40
505    27
506    46
507    18
508    27
509    23
510    34
511    22
512    29
513    43
514    27
515    53
516    53
517    24
518    49
519    22
520    62
521    19
522    36
523    50
524    56
525    27
526    30
527    33
528    18
529    47
530    29
531    30
532    20
533    43
534    20
535    45
536    38
537    36
538    31
539    53
540    28
541    19
542    21
543    33
544    44
545    27
546    36
547    50
548    51
549    42
550    16
551    25
552    45
553    58
554    32
555    29
556    35
557    30
558    56
559    69
560    32
561    23
562    54
563    39
564    65
565    40
566    20
567    24
568    39
569    34
570    26
571    34
572    51
573    68
574    56
575    33
576    48
577    36
578    31
579    32
580    16
581    37
582    17
583    44
584    25
585    69
586    20
587    26
588    18
589    21
590    50
591    57
592    18
593    31
594    46
595    25
596    20
597    23
598    40
599    22
600    34
601    19
602    47
603    21
604    39
605    33
606    28
607    49
608    22
609    13
610    22
611    46
612    36
613    37
614    54
615    38
616    55
617    27
618    15
619    17
620    18
621    17
622    25
623    50
624    19
625    27
626    23
627    24
628    13
629    46
630    26
631    18
632    18
633    35
634    39
635    22
636    47
637    30
638    45
639    42
640    20
641    24
642    18
643    39
644    51
645    27
646    17
647    40
648    43
649    20
650    42
651    65
652    35
653    31
654    27
655    50
656    48
657    26
658    33
659    31
660    26
661    28
662    55
663    26
664    30
665    25
666    44
667    35
668    29
669    37
670    30
671    21
672    54
673    51
674    13
675    34
676    30
677    20
678    50
679    20
680    33
681    44
682    23
683    42
684    28
685    32
686    32
687    31
688    37
689    25
690    35
691    34
692    34
693    43
694    60
695    26
696    55
697    25
698    28
699    44
700    17
701    51
702    37
703    26
704    51
705    21
706    23
707    56
708    26
709    21
710    19
711    22
712    22
713    42
714    26
715    21
716    36
717    24
718    42
719    37
720    49
721    24
722    50
723    26
724    31
725    21
726    25
727    25
728    58
729    19
730    31
731    41
732    28
733    44
734    25
735    29
736    48
737    30
738    35
739    35
740    25
741    25
742    35
743    31
744    35
745    42
746    25
747    19
748    28
749    33
750    28
751    24
752    60
753    56
754    59
755    44
756    30
757    26
758    27
759    20
760    35
761    17
762    32
763    27
764    27
765    31
766    42
767    70
768    29
769    39
770    28
771    26
772    50
773    20
774    30
775    46
776    30
777    63
778    34
779    31
780    49
781    20
782    21
783    30
784    47
785    32
786    36
787    18
788    51
789    29
790    27
791    31
792    40
793    22
794    32
795    30
796    32
797    44
798    40
799    49
800    25
801    22
802    35
803    70
804    39
805    27
806    27
807    41
808    45
809    50
810    55
811    40
812    22
813    14
814    30
815    32
816    34
817    19
818    28
819    59
820    22
821    37
822    29
823    27
824    31
825    44
826    28
827    23
828    28
829    48
830    46
831    21
832    24
833    34
834    26
835    44
836    44
837    36
838    23
839    38
840    39
841    45
842    40
843    35
844    22
845    64
846    27
847    29
848    46
849    15
850    34
851    18
852    46
853    49
854    29
855    53
856    43
857    35
858    63
859    18
860    70
861    38
862    25
863    17
864    27
865    25
866    45
867    24
868    21
869    30
870    22
871    31
872    19
873    48
874    36
875    24
876    41
877    30
878    50
879    33
880    13
881    39
882    35
883    49
884    44
885    30
886    20
887    14
888    41
889    24
890    32
891    51
892    36
893    25
894    47
895    31
896    28
897    30
898    23
899    32
900    60
901    38
902    45
903    28
904    17
905    27
906    45
907    25
908    44
909    50
910    28
911    37
912    51
913    27
914    44
915    50
916    27
917    22
918    40
919    25
920    30
921    20
922    29
923    21
924    29
925    18
926    49
927    23
928    21
929    44
930    28
931    60
932    58
933    28
934    61
935    42
936    24
937    48
938    38
939    26
940    32
941    20
942    48
943    22
Name: age, dtype: int64>

In [59]:
# q) Age with least occurence
df.age.value_counts().tail()

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64

In [ ]:
# r) Add new salary column with initial value of 0

df['salary'] = 0
df.head()

         age gender  occupation zip_code  salary
user_id
1         24      M  technician    85711       0
2         53      F       other    94043       0
3         23      M      writer    32067       0
4         24      M  technician    43537       0
5         33      F       other    15213       0

In [67]:
# s) Set salary of each user to 100 multiplied by user's age

df['salary'] = df['age'] * 100
df.head()

         age gender  occupation zip_code  salary
user_id
1         24      M  technician    85711    2400
2         53      F       other    94043    5300
3         23      M      writer    32067    2300
4         24      M  technician    43537    2400
5         33      F       other    15213    3300